name: "Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Build
        run: go build .

  check-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Generate documentation
        run: go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: |
          echo "Documentation is not up to date"
          exit 1